package com.zzcar.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zzcar.zzc.models.CountyMode;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COUNTY_MODE".
*/
public class CountyModeDao extends AbstractDao<CountyMode, Void> {

    public static final String TABLENAME = "COUNTY_MODE";

    /**
     * Properties of entity CountyMode.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Parentid = new Property(0, int.class, "parentid", false, "PARENTID");
        public final static Property First_letter = new Property(1, String.class, "first_letter", false, "FIRST_LETTER");
        public final static Property Full_name = new Property(2, String.class, "full_name", false, "FULL_NAME");
        public final static Property Id = new Property(3, int.class, "id", false, "ID");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property Region_name = new Property(5, String.class, "region_name", false, "REGION_NAME");
    }


    public CountyModeDao(DaoConfig config) {
        super(config);
    }
    
    public CountyModeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COUNTY_MODE\" (" + //
                "\"PARENTID\" INTEGER NOT NULL ," + // 0: parentid
                "\"FIRST_LETTER\" TEXT," + // 1: first_letter
                "\"FULL_NAME\" TEXT," + // 2: full_name
                "\"ID\" INTEGER NOT NULL ," + // 3: id
                "\"NAME\" TEXT," + // 4: name
                "\"REGION_NAME\" TEXT);"); // 5: region_name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COUNTY_MODE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CountyMode entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getParentid());
 
        String first_letter = entity.getFirst_letter();
        if (first_letter != null) {
            stmt.bindString(2, first_letter);
        }
 
        String full_name = entity.getFull_name();
        if (full_name != null) {
            stmt.bindString(3, full_name);
        }
        stmt.bindLong(4, entity.getId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String region_name = entity.getRegion_name();
        if (region_name != null) {
            stmt.bindString(6, region_name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CountyMode entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getParentid());
 
        String first_letter = entity.getFirst_letter();
        if (first_letter != null) {
            stmt.bindString(2, first_letter);
        }
 
        String full_name = entity.getFull_name();
        if (full_name != null) {
            stmt.bindString(3, full_name);
        }
        stmt.bindLong(4, entity.getId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String region_name = entity.getRegion_name();
        if (region_name != null) {
            stmt.bindString(6, region_name);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public CountyMode readEntity(Cursor cursor, int offset) {
        CountyMode entity = new CountyMode( //
            cursor.getInt(offset + 0), // parentid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // first_letter
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // full_name
            cursor.getInt(offset + 3), // id
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // region_name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CountyMode entity, int offset) {
        entity.setParentid(cursor.getInt(offset + 0));
        entity.setFirst_letter(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFull_name(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setId(cursor.getInt(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setRegion_name(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(CountyMode entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(CountyMode entity) {
        return null;
    }

    @Override
    public boolean hasKey(CountyMode entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
