package com.zzcar.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zzcar.zzc.models.CarfactoryDto;
import com.zzcar.zzc.models.CityModel;
import com.zzcar.zzc.models.CityModelCountry;
import com.zzcar.zzc.models.CountyMode;
import com.zzcar.zzc.models.MyEaseUser;
import com.zzcar.zzc.models.ProvenceModel;
import com.zzcar.zzc.models.ProvenceModelCountry;
import com.zzcar.zzc.networks.responses.BrandListResponse;
import com.zzcar.zzc.networks.responses.CarSeriesResponse;

import com.zzcar.greendao.CarfactoryDtoDao;
import com.zzcar.greendao.CityModelDao;
import com.zzcar.greendao.CityModelCountryDao;
import com.zzcar.greendao.CountyModeDao;
import com.zzcar.greendao.MyEaseUserDao;
import com.zzcar.greendao.ProvenceModelDao;
import com.zzcar.greendao.ProvenceModelCountryDao;
import com.zzcar.greendao.BrandListResponseDao;
import com.zzcar.greendao.CarSeriesResponseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig carfactoryDtoDaoConfig;
    private final DaoConfig cityModelDaoConfig;
    private final DaoConfig cityModelCountryDaoConfig;
    private final DaoConfig countyModeDaoConfig;
    private final DaoConfig myEaseUserDaoConfig;
    private final DaoConfig provenceModelDaoConfig;
    private final DaoConfig provenceModelCountryDaoConfig;
    private final DaoConfig brandListResponseDaoConfig;
    private final DaoConfig carSeriesResponseDaoConfig;

    private final CarfactoryDtoDao carfactoryDtoDao;
    private final CityModelDao cityModelDao;
    private final CityModelCountryDao cityModelCountryDao;
    private final CountyModeDao countyModeDao;
    private final MyEaseUserDao myEaseUserDao;
    private final ProvenceModelDao provenceModelDao;
    private final ProvenceModelCountryDao provenceModelCountryDao;
    private final BrandListResponseDao brandListResponseDao;
    private final CarSeriesResponseDao carSeriesResponseDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        carfactoryDtoDaoConfig = daoConfigMap.get(CarfactoryDtoDao.class).clone();
        carfactoryDtoDaoConfig.initIdentityScope(type);

        cityModelDaoConfig = daoConfigMap.get(CityModelDao.class).clone();
        cityModelDaoConfig.initIdentityScope(type);

        cityModelCountryDaoConfig = daoConfigMap.get(CityModelCountryDao.class).clone();
        cityModelCountryDaoConfig.initIdentityScope(type);

        countyModeDaoConfig = daoConfigMap.get(CountyModeDao.class).clone();
        countyModeDaoConfig.initIdentityScope(type);

        myEaseUserDaoConfig = daoConfigMap.get(MyEaseUserDao.class).clone();
        myEaseUserDaoConfig.initIdentityScope(type);

        provenceModelDaoConfig = daoConfigMap.get(ProvenceModelDao.class).clone();
        provenceModelDaoConfig.initIdentityScope(type);

        provenceModelCountryDaoConfig = daoConfigMap.get(ProvenceModelCountryDao.class).clone();
        provenceModelCountryDaoConfig.initIdentityScope(type);

        brandListResponseDaoConfig = daoConfigMap.get(BrandListResponseDao.class).clone();
        brandListResponseDaoConfig.initIdentityScope(type);

        carSeriesResponseDaoConfig = daoConfigMap.get(CarSeriesResponseDao.class).clone();
        carSeriesResponseDaoConfig.initIdentityScope(type);

        carfactoryDtoDao = new CarfactoryDtoDao(carfactoryDtoDaoConfig, this);
        cityModelDao = new CityModelDao(cityModelDaoConfig, this);
        cityModelCountryDao = new CityModelCountryDao(cityModelCountryDaoConfig, this);
        countyModeDao = new CountyModeDao(countyModeDaoConfig, this);
        myEaseUserDao = new MyEaseUserDao(myEaseUserDaoConfig, this);
        provenceModelDao = new ProvenceModelDao(provenceModelDaoConfig, this);
        provenceModelCountryDao = new ProvenceModelCountryDao(provenceModelCountryDaoConfig, this);
        brandListResponseDao = new BrandListResponseDao(brandListResponseDaoConfig, this);
        carSeriesResponseDao = new CarSeriesResponseDao(carSeriesResponseDaoConfig, this);

        registerDao(CarfactoryDto.class, carfactoryDtoDao);
        registerDao(CityModel.class, cityModelDao);
        registerDao(CityModelCountry.class, cityModelCountryDao);
        registerDao(CountyMode.class, countyModeDao);
        registerDao(MyEaseUser.class, myEaseUserDao);
        registerDao(ProvenceModel.class, provenceModelDao);
        registerDao(ProvenceModelCountry.class, provenceModelCountryDao);
        registerDao(BrandListResponse.class, brandListResponseDao);
        registerDao(CarSeriesResponse.class, carSeriesResponseDao);
    }
    
    public void clear() {
        carfactoryDtoDaoConfig.clearIdentityScope();
        cityModelDaoConfig.clearIdentityScope();
        cityModelCountryDaoConfig.clearIdentityScope();
        countyModeDaoConfig.clearIdentityScope();
        myEaseUserDaoConfig.clearIdentityScope();
        provenceModelDaoConfig.clearIdentityScope();
        provenceModelCountryDaoConfig.clearIdentityScope();
        brandListResponseDaoConfig.clearIdentityScope();
        carSeriesResponseDaoConfig.clearIdentityScope();
    }

    public CarfactoryDtoDao getCarfactoryDtoDao() {
        return carfactoryDtoDao;
    }

    public CityModelDao getCityModelDao() {
        return cityModelDao;
    }

    public CityModelCountryDao getCityModelCountryDao() {
        return cityModelCountryDao;
    }

    public CountyModeDao getCountyModeDao() {
        return countyModeDao;
    }

    public MyEaseUserDao getMyEaseUserDao() {
        return myEaseUserDao;
    }

    public ProvenceModelDao getProvenceModelDao() {
        return provenceModelDao;
    }

    public ProvenceModelCountryDao getProvenceModelCountryDao() {
        return provenceModelCountryDao;
    }

    public BrandListResponseDao getBrandListResponseDao() {
        return brandListResponseDao;
    }

    public CarSeriesResponseDao getCarSeriesResponseDao() {
        return carSeriesResponseDao;
    }

}
